version: '2'

services:
  ampq:
    restart: unless-stopped
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  import:
    image: netpascal0123/wallabag_2_leanote
    command: export.js --client_id=$CLIENT_ID --client_secret=$CLIENT_SECRET --login=$USERNAME  --password=$PASSWORD  --host=$WALLABAG_HOST
    depends_on:
      - ampq

  export:
    image: netpascal0123/wallabag_2_leanote
    command: import.js --notebook=$NOTEBOOK --email=$EMAIL --pwd=$PWD --host=$LEANOTE_HOST
    depends_on:
      - ampq
